version: "3.2"
services:
    db:
      image: mysql:8
      volumes:
        - db_data:/var/lib/mysql
        - ./mysql-dump:/docker-entrypoint-initdb.d
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: '000000000'
        MYSQL_DATABASE: mydb
      ports:
        - 3307:3306
      
volumes:
    db_data: {}
